[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/api/*"
  to = "https://hhmc.aiofauna.com/api/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "https://hhmc.aiofauna.com/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
