/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    Explorer: typeof import('./components/Explorer.vue')['default']
    McBot: typeof import('./components/McBot.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NoteColumn: typeof import('./components/NoteColumn.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    Piano: typeof import('./components/Piano.vue')['default']
    PianoColumn: typeof import('./components/PianoColumn.vue')['default']
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sequencer: typeof import('./components/Sequencer.vue')['default']
    SequencerControls: typeof import('./components/SequencerControls.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
    Visualizer: typeof import('./components/Visualizer.vue')['default']
    WebSocket: typeof import('./components/WebSocket.vue')['default']
  }
}
